In [1]:
pip install yfinance

Collecting yfinance
  Downloading yfinance-0.2.66-py2.py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: pandas>=1.3.0 in c:\users\usuario\anaconda3\lib\site-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in c:\users\usuario\anaconda3\lib\site-packages (from yfinance) (1.26.4)
Requirement already satisfied: requests>=2.31 in c:\users\usuario\anaconda3\lib\site-packages (from yfinance) (2.32.3)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.12.tar.gz (19 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\usuario\anaconda3\lib\site-packages (from yfinance) (3.10.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\usuario\anaconda3\lib\site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\usuario\anaconda3\lib\site-packages (from yfinance) (2.4.2)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-3.18.3.tar.gz (3.0 MB)
     ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
     ---------------------------------------- 3.0/3.0 MB 43.9 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\usuario\anaconda3\lib\site-packages (from yfinance) (4.12.3)
Collecting curl_cffi>=0.7 (from yfinance)
  Downloading curl_cffi-0.14.0-cp39-abi3-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\usuario\anaconda3\lib\site-packages (from yfinance) (6.32.1)
Collecting websockets>=13.0 (from yfinance)
  Downloading websockets-15.0.1-cp312-cp312-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: soupsieve>1.2 in c:\users\usuario\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: cffi>=1.12.0 in c:\users\usuario\anaconda3\lib\site-packages (from curl_cffi>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\usuario\anaconda3\lib\site-packages (from curl_cffi>=0.7->yfinance) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\usuario\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\usuario\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\usuario\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\usuario\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\usuario\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.2.3)
Requirement already satisfied: pycparser in c:\users\usuario\anaconda3\lib\site-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.21)
Requirement already satisfied: six>=1.5 in c:\users\usuario\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.16.0)
Downloading yfinance-0.2.66-py2.py3-none-any.whl (123 kB)
Downloading curl_cffi-0.14.0-cp39-abi3-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 30.1 MB/s eta 0:00:00
Downloading websockets-15.0.1-cp312-cp312-win_amd64.whl (176 kB)
Building wheels for collected packages: multitasking, peewee
  Building wheel for multitasking (setup.py): started
  Building wheel for multitasking (setup.py): finished with status 'done'
  Created wheel for multitasking: filename=multitasking-0.0.12-py3-none-any.whl size=15617 sha256=513c5df63af29df4aebf55fce2fd3158ee9114c2e9ac050918db804171f5c1ef
  Stored in directory: c:\users\usuario\appdata\local\pip\cache\wheels\cc\bd\6f\664d62c99327abeef7d86489e6631cbf45b56fbf7ef1d6ef00
  Building wheel for peewee (pyproject.toml): started
  Building wheel for peewee (pyproject.toml): finished with status 'done'
  Created wheel for peewee: filename=peewee-3.18.3-py3-none-any.whl size=139181 sha256=8f1ebf68053a1b47fb3bd9800891e9f4a90ff9192b98c9415d2efc328cbbedee
  Stored in directory: c:\users\usuario\appdata\local\pip\cache\wheels\e2\48\b6\675a31c56e50b8b343e1ffbb1d9209f0d95025e2cfa0bbeeed
Successfully built multitasking peewee
Installing collected packages: peewee, multitasking, websockets, curl_cffi, yfinance
Successfully installed curl_cffi-0.14.0 multitasking-0.0.12 peewee-3.18.3 websockets-15.0.1 yfinance-0.2.66
Note: you may need to restart the kernel to use updated packages.

In [1]:
import yfinance as yf

In [17]:
dat = yf.Ticker("MSFT")

In [57]:
msft = dat.history(period='5y',auto_adjust= False)

In [59]:
msft

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
2020-12-17 00:00:00-05:00,219.869995,220.889999,217.919998,219.419998,210.542236,32515800,0.0,0.0
2020-12-18 00:00:00-05:00,218.589996,219.690002,216.020004,218.589996,209.745819,63354900,0.0,0.0
2020-12-21 00:00:00-05:00,217.550003,224.000000,217.279999,222.589996,213.583923,37181900,0.0,0.0
2020-12-22 00:00:00-05:00,222.690002,225.630005,221.850006,223.940002,214.879318,22612200,0.0,0.0
2020-12-23 00:00:00-05:00,223.110001,223.559998,220.800003,221.020004,212.077499,18699600,0.0,0.0
...,...,...,...,...,...,...,...,...
2025-12-11 00:00:00-05:00,476.630005,486.029999,475.859985,483.470001,483.470001,24669200,0.0,0.0
2025-12-12 00:00:00-05:00,479.820007,482.450012,476.339996,478.529999,478.529999,21248100,0.0,0.0
2025-12-15 00:00:00-05:00,480.100006,480.720001,472.519989,474.820007,474.820007,23727700,0.0,0.0
2025-12-16 00:00:00-05:00,471.910004,477.890015,470.880005,476.390015,476.390015,20682600,0.0,0.0
2025-12-17 00:00:00-05:00,476.904999,479.000000,475.220001,478.600006,478.600006,9481990,0.0,0.0

In [61]:
msft['SMA21'] = msft['Adj Close'].rolling(21).mean()

In [63]:
msft

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,SMA21
Date,,,,,,,,,
2020-12-17 00:00:00-05:00,219.869995,220.889999,217.919998,219.419998,210.542236,32515800,0.0,0.0,NaN
2020-12-18 00:00:00-05:00,218.589996,219.690002,216.020004,218.589996,209.745819,63354900,0.0,0.0,NaN
2020-12-21 00:00:00-05:00,217.550003,224.000000,217.279999,222.589996,213.583923,37181900,0.0,0.0,NaN
2020-12-22 00:00:00-05:00,222.690002,225.630005,221.850006,223.940002,214.879318,22612200,0.0,0.0,NaN
2020-12-23 00:00:00-05:00,223.110001,223.559998,220.800003,221.020004,212.077499,18699600,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...
2025-12-11 00:00:00-05:00,476.630005,486.029999,475.859985,483.470001,483.470001,24669200,0.0,0.0,488.093871
2025-12-12 00:00:00-05:00,479.820007,482.450012,476.339996,478.529999,478.529999,21248100,0.0,0.0,486.586482
2025-12-15 00:00:00-05:00,480.100006,480.720001,472.519989,474.820007,474.820007,23727700,0.0,0.0,485.275540
2025-12-16 00:00:00-05:00,471.910004,477.890015,470.880005,476.390015,476.390015,20682600,0.0,0.0,483.711879
2025-12-17 00:00:00-05:00,476.904999,479.000000,475.220001,478.600006,478.600006,9481990,0.0,0.0,482.381311

In [65]:
msft = msft.dropna()
msft

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,SMA21
Date,,,,,,,,,
2021-01-19 00:00:00-05:00,213.750000,216.979996,212.630005,216.440002,207.682800,30480900,0.0,0.0,210.099914
2021-01-20 00:00:00-05:00,217.699997,225.789993,217.289993,224.339996,215.263138,37777300,0.0,0.0,210.324719
2021-01-21 00:00:00-05:00,224.699997,226.300003,222.419998,224.970001,215.867676,30709400,0.0,0.0,210.616236
2021-01-22 00:00:00-05:00,227.080002,230.070007,225.800003,225.949997,216.808014,30172700,0.0,0.0,210.769764
2021-01-25 00:00:00-05:00,229.119995,229.779999,224.220001,229.529999,220.243179,33152100,0.0,0.0,211.025186
...,...,...,...,...,...,...,...,...,...
2025-12-11 00:00:00-05:00,476.630005,486.029999,475.859985,483.470001,483.470001,24669200,0.0,0.0,488.093871
2025-12-12 00:00:00-05:00,479.820007,482.450012,476.339996,478.529999,478.529999,21248100,0.0,0.0,486.586482
2025-12-15 00:00:00-05:00,480.100006,480.720001,472.519989,474.820007,474.820007,23727700,0.0,0.0,485.275540
2025-12-16 00:00:00-05:00,471.910004,477.890015,470.880005,476.390015,476.390015,20682600,0.0,0.0,483.711879
2025-12-17 00:00:00-05:00,476.904999,479.000000,475.220001,478.600006,478.600006,9481990,0.0,0.0,482.381311

In [67]:
prueba = type(yf.download(['MSFT', 'AAPL', 'GOOG'], period='1mo'))
prueba

C:\Users\Usuario\AppData\Local\Temp\ipykernel_22240\1437727654.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  prueba = type(yf.download(['MSFT', 'AAPL', 'GOOG'], period='1mo'))
[*********************100%***********************]  3 of 3 completed

pandas.core.frame.DataFrame

In [69]:
array =type(["hola","chau"])
array

list

In [71]:
mi_lista = ["hola", "chau"]

print(type(mi_lista))

<class 'list'>